name: Build and push artifact to Docker Hub
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Setup BATS
      uses: mig4/setup-bats@v1
      with:
        bats-version: 1.7.0

    - name: Setup Bats libs
      uses: brokenpip3/setup-bats-libs@0.1.0

    - name: Check out code
      uses: actions/checkout@v1

    - name: Install Trivy
      run: |
        curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin v${{ env.TRIVY_VERSION }}

    - name: Test
      run: BATS_LIB_PATH=${{ env.BATS_LIB_PATH }} bats --recursive --timing .

    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: deepaksai678/hello-world:latest
